# Generated by Django 5.1.4 on 2025-03-11 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('industry_type', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Education', 'Education'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=50)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('current_semester', models.IntegerField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('skills', models.TextField(help_text='Enter skills separated by commas')),
                ('certifications', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('salary_package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Internship', 'Internship'), ('Part-time', 'Part-time')], max_length=20)),
                ('bond_period', models.PositiveIntegerField(blank=True, help_text='Duration in months', null=True)),
                ('job_location', models.CharField(max_length=255)),
                ('cgpa_requirement', models.DecimalField(decimal_places=2, help_text='Minimum CGPA required', max_digits=3)),
                ('skills_required', models.TextField()),
                ('backlog_allowed', models.CharField(choices=[('Yes', 'Yes'), ('NO', 'NO')], max_length=20)),
                ('batch_eligible', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=50)),
                ('selection_process', models.TextField(help_text='Stages like Aptitude Test, Coding Test, Interviews')),
                ('application_deadline', models.DateField()),
                ('drive_date', models.DateField()),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='home.company')),
                ('applied_students', models.ManyToManyField(blank=True, related_name='applied_drives', to='home.studentprofile')),
                ('selected_students', models.ManyToManyField(blank=True, related_name='selected_drives', to='home.studentprofile')),
            ],
        ),
    ]
